import {
  Utensils,
  Car,
  House,
  Zap,
  Clapperboard,
  HeartPulse,
  Shirt,
  GraduationCap,
  Smartphone,
  Gift,
  Plane,
  ShoppingBag,
  Wallet,
  Banknote,
  Laptop,
  TrendingUp,
  Award,
  PiggyBank,
  CircleEllipsis,
  Coffee,
  Dumbbell,
  Baby,
  PawPrint,
  Wrench,
  Building2,
  CreditCard,
  Bus,
  Fuel,
  type LucideIcon,
} from "lucide-react";

/** Registry mapping string keys (stored in data) to Lucide icon components. */
export const ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  coffee: Coffee,
  car: Car,
  bus: Bus,
  fuel: Fuel,
  house: House,
  building: Building2,
  zap: Zap,
  clapperboard: Clapperboard,
  heartPulse: HeartPulse,
  shirt: Shirt,
  graduationCap: GraduationCap,
  smartphone: Smartphone,
  gift: Gift,
  plane: Plane,
  shoppingBag: ShoppingBag,
  wallet: Wallet,
  banknote: Banknote,
  laptop: Laptop,
  trendingUp: TrendingUp,
  award: Award,
  piggyBank: PiggyBank,
  dumbbell: Dumbbell,
  baby: Baby,
  pawPrint: PawPrint,
  wrench: Wrench,
  creditCard: CreditCard,
  ellipsis: CircleEllipsis,
};

export const ICON_KEYS = Object.keys(ICONS);

export function getIcon(key: string): LucideIcon {
  return ICONS[key] ?? CircleEllipsis;
}
